language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: B/50USh2LkPVGfLecGYX7Pie1RIU659Wix6qpgFJ4dI49BiB57AmtnHeMVIRP/7l3r9yiKaGn/+pR2G9f6bW57XwOn5akzvA0X2IHKCS4/QB4G/qneLSHpsxLjbxnqS2NgtXCLJQa8FDa7ZBxfzn+UGNRQiQXPfRmiwHAY08IKWt27zrj1k3iBQpcyQH8iAZEsnk/UhMofLN7dYuYebP4uk4s6MprpJ4+PYNlu99k3dWn43fJJtL0iUe3T1UMo3TvlqUzE04QV+cdhfLlqssLZ8Vraf4mzn0O6L12RDPiWwVgfatHdANNg5oChXzBwlN8g9gyiuRXpTYk3T19DmUxzrr1bS1NgyWOXlvk4scv5Vj5nxb7IQDP/0NhELBhJHmlM5l6v9z69Eace/O+4/DJBlj2zndBhgC7N0wmAy635VDX7mv+Ev2zh6YZbqzqDnyntMHFySVWi4BLPDfACP3oIGzPQhfzLec4r0bjg4rsgeSBYs43oTZ9bqz8DDedrSK52X3qxA0h0p0ZzxJQHwAfobaf7qiDDoN+vvyfebhhGV+bv33rHHnJ/Qlo4ZdL2KzyOYNARnJBgi8t1A72DSrE/WlEiexmkt7/FZYq/tl1jtW+um2+azkJGWVMykA/uGjeCYcxsaIubkMVBT4vRwPunze+n2Ll9/b0Biibf4j7KU=
